name: 'luacheck'
description: 'Run luacheck.'
inputs:
  path:
    description: 'Path to .luacheckrc'
    required: false
    default: '.'
  args:
    description: 'Arguments to luacheck'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    PATH_LUACHECKRC: ${{ inputs.path }}
  args:
    - ${{ inputs.args }}